#!/bin/bash
#
# This wrapper script takes the environment variables currently set by
# Eric's jenkins scripts and puts everything into the config file.
# 

if [ $# -ne 2 ]; then
	cat >&2 <<-EOF
	Usage:
	$0 template config-path
EOF
	exit 1
fi

nodes_file=$1
TWOPENCE_CONFIG_PATH=$2

cp /dev/null $TWOPENCE_CONFIG_PATH
export TWOPENCE_CONFIG_PATH

nodes=`sed -r 's/^node[[:space:]]+(.*)/\1/;t;d' $nodes_file`

for node in $nodes; do
	susetest config add-node $node

	NODE=`echo $node|tr a-z A-Z`

	eval target=\"\$TARGET_$NODE\"
	if [ -n "$target" ]; then
		susetest config node-set-attr "$node" target="$target"
	else
		echo "No twopence target for node \"$node\"" >&2
		exit 1
	fi

	eval value=\"\$EXTERNAL_IP_$NODE\"
	if [ -n "$value" ]; then
		susetest config node-set-attr "$node" ipaddr="$value"
	fi

	eval value=\"\$EXTERNAL_IP6_$NODE\"
	if [ -n "$value" ]; then
		susetest config node-set-attr "$node" ip6addr="$value"
	fi

	eval value=\"\$SYSTEM_$NODE\"
	if [ -n "$value" ]; then
		susetest config node-set-attr "$node" system="$value"
	fi
done

if [ -n "$WORKSPACE" ]; then
	susetest config set-attr workspace="$WORKSPACE"
	susetest config set-attr report="$WORKSPACE/report.xml"
fi
