#!/bin/bash
#
# This wrapper script takes the environment variables currently set by
# Eric's jenkins scripts and puts everything into the config file.
# 

if [ $# -ne 2 ]; then
	cat >&2 <<-EOF
	Usage:
	$0 template config-path
EOF
	exit 1
fi

template=$1
TWOPENCE_CONFIG_PATH=$2

cp $template $TWOPENCE_CONFIG_PATH
export TWOPENCE_CONFIG_PATH

for node in `susetest config node-names`; do
	eval target=\"\$TARGET_$node\"
	if [ -n "$target" ]; then
		susetest config node-set-attr "$node" target="$target"
	else
		echo "No twopence target for node \"$node\"" >&2
		exit 1
	fi

	eval value=\"\$IP_$node\"
	if [ -n "$value" ]; then
		susetest config node-set-attr "$node" ipaddr="$value"
	fi

	eval value=\"\$IP6_$node\"
	if [ -n "$value" ]; then
		susetest config node-set-attr "$node" ip6addr="$value"
	fi

	eval value=\"\$SYSTEM_$node\"
	if [ -n "$value" ]; then
		susetest config node-set-attr "$node" system="$value"
	fi

	for pkg in `susetest config node-get-attr "$node" packages`; do
		echo "Need to install $pkg on node $node"
		twopence_command "$target" "zypper install $pkg"
	done
done
